name: Build Firmware


on:
  push:
    branches: [ main ]


env:
  NO_PPA: 1


jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Mongoose OS CLI
        run: |
          export NO_PPA=1
          curl -fsSL https://mongoose-os.com/downloads/mos/install.sh | /bin/bash
          echo "$HOME/.mos/bin" >> $GITHUB_PATH
          ls -la ~/.mos/bin/

      - name: Build Firmware
        run: |
          mos build --local

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: firmware
          path: build/fw.zip

